---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1004086/public_html/
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp bootstrap.min.css $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
