---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1004086/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
